import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { htmlToText, mathmlToTex, parseSections, textToSections, tidySections } from '../../src/clients/arxiv_html.js';

const FIXTURE = readFileSync(new URL('../fixtures/arxiv_html_latexml.html', import.meta.url), 'utf8');

describe('mathmlToTex', () => {
  it('inline math becomes $X$ and decodes entities in alttext', () => {
    const html = 'so <math alttext="F&gt;3\\sigma" display="inline"><mi>F</mi></math> holds';
    expect(mathmlToTex(html)).toBe('so $F>3\\sigma$ holds');
  });

  it('display="block" becomes $$X$$', () => {
    const html = '<math display="block" alttext="E=mc^{2}"><mi>E</mi></math>';
    expect(mathmlToTex(html)).toBe('$$E=mc^{2}$$');
  });

  it('falls back to the x-tex annotation when alttext is absent, and leaves unknown math alone', () => {
    const withAnn = '<math><semantics><mi>x</mi><annotation encoding="application/x-tex">x^{2}</annotation></semantics></math>';
    expect(mathmlToTex(withAnn)).toBe('$x^{2}$');
    const bare = '<math><mi>x</mi></math>';
    expect(mathmlToTex(bare)).toBe(bare);
  });

  it('htmlToText keeps < and > of the TeX literally (they are not tags)', () => {
    const text = htmlToText('<p>if <math alttext="a&lt;b&amp;&amp;c&gt;d">x</math> then</p>');
    expect(text).toBe('if $a<b&&c>d$ then');
  });
});

describe('parseSections (LaTeXML fixture)', () => {
  const sections = parseSections(FIXTURE);

  it('lists abstract, sections, subsections, appendix and bibliography in document order', () => {
    expect(sections.map(s => [s.id, s.level])).toEqual([
      ['abstract', 1], ['S1', 1], ['S1.SS1', 2], ['S1.SS2', 2], ['S2', 1], ['A1', 1], ['bib', 1],
    ]);
    expect(sections.map(s => s.title)).toEqual([
      'Abstract', '1 Introduction', '1.1 Previous work', '1.2 This work', '2 Method',
      'Appendix A Sample table', 'References',
    ]);
  });

  it('a parent section excludes its subsections, and text after them is kept', () => {
    const s1 = sections.find(s => s.id === 'S1')!;
    expect(s1.text).toContain('Protoplanetary disks host');
    expect(s1.text).toContain('The remainder of the paper is organised');
    expect(s1.text).not.toContain('flux threshold');
    expect(s1.text).not.toContain('re-reduce ALMA');
    expect(sections.find(s => s.id === 'S1.SS1')!.text).toContain('flux threshold');
  });

  it('renders math as TeX, inline and display, with entities decoded', () => {
    expect(sections.find(s => s.id === 'abstract')!.text).toContain('$N=120$');
    expect(sections.find(s => s.id === 'S1.SS1')!.text).toContain('$F>3\\sigma$');
    expect(sections.find(s => s.id === 'S2')!.text).toContain('$$M_{\\rm dust}=\\frac{F_{\\nu}d^{2}}{\\kappa_{\\nu}B_{\\nu}(T)}$$');
    for (const s of sections) expect(s.text).not.toMatch(/<\/?(math|semantics|annotation)/);
  });

  it('keeps front matter and the page footer out of every section', () => {
    const all = sections.map(s => s.text).join('\n');
    expect(all).not.toContain('A. Author');
    expect(all).not.toContain('Generated by LaTeXML');
  });

  it('returns nothing for a page without LaTeXML sections', () => {
    expect(parseSections('<html><body><h1>T</h1><p>x</p></body></html>')).toEqual([]);
  });
});

describe('textToSections (PDF heuristics)', () => {
  const text = [
    'A Title', 'Some Author', '', 'Abstract', 'We study things.', '',
    '1 Introduction', 'Intro text here.', '', '2.1 Data', 'Data text.', '',
    '3 We then show that the result holds for all cases, and more.', 'Not a heading (too long, has comma).', '',
    'Conclusions', 'Done.', '', 'References', '[1] A. Author 2020.', '4 Appendix after refs', 'x',
  ].join('\n');
  const sections = textToSections(text);

  it('finds bare, numbered headings and stops at References', () => {
    expect(sections.map(s => s.title)).toEqual([
      'Preamble', 'Abstract', 'Introduction', 'Data', 'Conclusions', 'References',
    ]);
    expect(sections.find(s => s.title === 'Data')).toMatchObject({ id: '2.1', level: 2 });
    expect(sections.find(s => s.id === '1')!.text).toContain('Intro text here.');
  });

  it('does not treat a numbered sentence as a heading, nor look past References', () => {
    expect(sections.find(s => s.title === 'Data')!.text).toContain('Not a heading');
    expect(sections.at(-1)!.text).toContain('4 Appendix after refs');
  });

  it('headingless text becomes one synthetic section; empty text none', () => {
    expect(textToSections('just words\nand more')).toMatchObject([{ id: '1', title: 'Full text' }]);
    expect(textToSections('  \n ')).toEqual([]);
  });

  it('duplicate numbering gets distinct ids', () => {
    const ids = textToSections('1 Intro\nx\n1 Intro\ny').map(s => s.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe('tidy section text', () => {
  it('collapses runs of spaces and tabs (cites, refs) but keeps newlines and the TeX inside $...$', () => {
    const html = '<p>Brown <span> </span> et al. <cite> (<a>2020</a>) </cite>   enables   <math alttext="a  b">x</math> here\t\tand there.</p><p>Next</p>';
    const text = htmlToText(html);
    expect(text).not.toMatch(/[ \t]{2,}/);
    expect(text).toContain('Brown et al. ( 2020 ) enables');
    expect(text).toContain('$a b$');
    expect(text).toContain('\n\nNext');
  });

  it('drops the heading that LaTeXML repeats as the first line of the section body', () => {
    const sections = parseSections(FIXTURE);
    const s1 = sections.find(s => s.id === 'S1')!;
    expect(s1.text.startsWith('Protoplanetary disks host')).toBe(true);
    expect(sections.find(s => s.id === 'abstract')!.text.startsWith('We measure dust masses')).toBe(true);
    expect(sections.find(s => s.id === 'A1')!.text).toBe('Full target list.');
    // a body that merely repeats the title later is not touched
    const odd = parseSections(
      '<section id="S1" class="ltx_section"><h2 class="ltx_title"><span class="ltx_tag">1 </span>Data</h2><p>Data are shown.</p></section>'
    );
    expect(odd[0].text).toBe('Data are shown.');
  });

  it('empty titles fall back to the id; a section with neither title nor text is skipped', () => {
    const out = tidySections([
      { id: 'S4.SS3', level: 2, title: '  ', text: 'Body.' },
      { id: 'S4.SS4', level: 2, title: '', text: ' ' },
      { id: 'S5', level: 1, title: 'Real', text: '' },
    ]);
    expect(out.map(s => [s.id, s.title])).toEqual([['S4.SS3', 'S4.SS3'], ['S5', 'Real']]);
  });
});
